import React from "react";
import Header from "./components/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Victory | El-Trivela",
  description: "Generated by create next app",
};

const TurfLayout = ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { slug: string };
}) => {
  return (
    <>
      <Header slug={params.slug} />
      {/* HEADER */}
      {/* DESCRIPTION PORTION */}
      <div className="flex m-auto w-2/3 justify-between items-start -mt-11">
        {children}
      </div>
    </>
  );
};

export default TurfLayout;
